version: "3.8"

networks:
  deploy-webapi-cosmosdb:
    driver: bridge

services:
  fakedoutshop.api:
    container_name: fakedoutshop-api
    build:
      context: .
      dockerfile: FakedOutShop.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-webapi-cosmosdb
    depends_on:
      - cosmosdb

  cosmosdb:
    container_name: cosmosdb-emulator
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    ports:
      - "5432:5432"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=11
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    networks:
      - deploy-webapi-cosmosdb
    volumes:
      - cosmosdb-data:/var/lib/cosmosdb

volumes:
  cosmosdb-data:
