name: CI - Build and Test ASP.NET Core App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # ⚠️ Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore apps/backend/FakedOutShop.sln

      - name: Build solution
        run: dotnet build apps/backend/FakedOutShop.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test apps/backend/FakedOutShop.sln --configuration Release --no-build --verbosity normal
